### PR TITLE
* add suport for customized Polr instances

### PR DESCRIPTION
**Pull request by allgood**
Hi,

I've changed a little your extension allowing it to use any Polr instance.

polr.me is an Open Source and very light URL shortener.

In order to run this changes with my instance of Polr I had to change a header of the response from the server, but I am sending patches to its authors also.

Best Regards,
Claudemir

### CODE REVIEW

**Comment by allgood** [comment]
This is the Issue I've opened on Polr project: https://github.com/cydrobolt/polr/issues/205

**Comment by Wassup789** [comment]
I would merge this however, I found some bugs and suggestions that need to be fixed.
- `#option_polr_show` and `#option_polr_hide` do not display properly when both user-inputted variables are empty. They can also be put under one element and using data-attributes and using the css `:after` tag (Just my personal preference, changing text using jQuery.text is viable too.)
- URLs should be validated using the `isValidUrl` function that is included in the settings.js
- The polr `apiKey`and `url` variables can be initalized within the `apiData`object itself.
- Add capitlization to the show/hide config

Other than that, this would be a great addition.

**Comment by allgood** [comment]
Thank you for your reply @Wassup789 , HTML and Javascript is not where I am good, so, you can think of my suggestion as a quick hack. Learning about data attributes right now!

The hiding of hide and show links when url and api are empty was intentional, since it will not work without them, I chose to show them until they are filled and saved.

Will try to do your suggestions and will get back here to post.

Best Regards,
Claudemir

**Comment by allgood** [comment]
Made some enhancements following your suggestions. Included also the display of `https://` before the url field, since I think it is wise to only use polr instances that support encryption.

**Comment by Wassup789** [comment]
Sorry for the late reply, there are some issues with how the base URL is displayed I can fix that. I recommend you make a pull request to the Polr repository about the CORS issue.

**Comment by allgood** [comment]
I will talk with the author again. Now that your extension have support to
it I can point it back!

Thank you!

Em ter, 30 de ago de 2016 às 18:16, Wassup789 notifications@github.com
escreveu:

**Pull request merged**
